import 'package:currency_converter/currancy_converter_material_page.dart';
// import 'package:currency_converter/lifecycleWidget.dart';
import 'package:flutter/material.dart';
import 'app_theme.dart';

void main() {
  runApp(const MyApp());
  // const is used to create a constant object...
  // to tell the compiler that the object is constant and immutable...
  // runApp is the function to start the flutter code...
  // widget is the building block of the flutter application...
  // Hot reload is a feature of flutter that allows you to see the changes in the code without restarting the application...

  // navigation is the process of moving from one screen to another screen...
  // Navigator is the class that is used to navigate between screens...
  // Navigator.push is the method that is used to navigate to a new screen...
  // Navigator.pop is the method that is used to navigate to the previous screen...
}

// types of widgets:
// 1. StatelessWidget
// 2. StatefulWidget
// 3. CupertinoWidget
// 4. MaterialWidget

// StatelessWidget:
// 1. It is a widget that does not change its state...
// 2. It is a widget that is immutable...
// 3. It is a widget that is stateless...

// StatefulWidget:
// 1. It is a widget that changes its state...
// 2. It is a widget that is mutable...
// 3. It is a widget that is stateful...

// CupertinoWidget:
// 1. It is a widget that is used to create a Cupertino style application...

// MaterialWidget:
// 1. It is a widget that is used to create a Material style application...

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    // MaterialApp is the widget that is used to create a Material style application...
    return MaterialApp(
        theme: lightTheme, home: CurreencyConverterMaterialPage());
  }
}

// Material Design is a design language developed by Google in 2014...
// It is a comprehensive guide for visual, motion, and interaction design across platforms and devices...
// It is a design language that is used to create a consistent and predictable user experience across different platforms and devices...

// Cupertino Design is a design language developed by Apple in 2010...
// It is a design language that is used to create a consistent and predictable user experience across different platforms and devices...